// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ZkBase} from "./ZkBase.sol";
import {OarkelPool, IProofVerifier} from "../src/OarkelPool.sol";
import {MockToken, RejectEth} from "./Mocks.sol";

/// End-to-end money paths with real UltraHonk proofs generated by the site's prover.
contract OarkelPoolProofsTest is ZkBase {
    MockToken internal token;
    address internal alice = makeAddr("alice");
    address internal bob = makeAddr("bob");

    function setUp() public {
        token = new MockToken();
        _deploy(token);
        vm.deal(address(this), 100 ether);
        token.mint(address(this), 1_000_000 ether);
        token.approve(address(pool), type(uint256).max);
    }

    function test_EthShroudThenUnshroudWithRelayer() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 777);
        assertEq(n.value, 0.9975 ether);
        assertEq(pool.ethFees(), 0.0025 ether);

        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.4 ether;
        s.recipient = alice;
        s.relayerAddr = relayer;
        s.relayerFee = 0.0002 ether;
        Spend memory sp = prove(s);

        vm.prank(relayer);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        assertEq(alice.balance, 0.4 ether - FLAT_ETH - 0.0002 ether);
        assertEq(relayer.balance, 0.0002 ether);
        assertEq(pool.ethFees(), 0.0025 ether + FLAT_ETH);
        assertTrue(pool.nullifierSpent(sp.args.nullifiers[0]));

        // Spend the change in a second proof: everything out.
        Note memory change = landed(sp, SIG_A);
        assertEq(change.value, 0.5975 ether);
        s.notes = one(change);
        s.exitValue = change.value;
        s.relayerFee = 0;
        s.relayerAddr = address(0);
        Spend memory sp2 = prove(s);
        pool.unshroud(sp2.proof, sp2.args, sp2.ext);
        landed(sp2, SIG_A);
        // Only fees remain in the pool, and anyone can sweep them to the fee sink.
        assertEq(address(pool).balance, pool.ethFees());
        pool.sweepEthFees();
        assertEq(feeSink.balance, 0.0025 ether + 2 * FLAT_ETH);
        assertEq(address(pool).balance, 0);
    }

    function test_PrivateSendPaysTransferFeeAndRelayer() public {
        Note memory n = shroud(SIG_A, 0, 2 ether, 1);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.paySig = SIG_B;
        s.payValue = 0.5 ether;
        s.exitValue = 0.0002 ether; // the relayer's cut
        s.relayerAddr = relayer;
        s.relayerFee = 0.0002 ether;
        Spend memory sp = prove(s);
        assertEq(sp.args.transferFee, 0.0005 ether, "10 bps of 0.5 ETH");

        uint256 feesBefore = pool.ethFees();
        // Anyone else landing this relayed proof is refused: only the named relayer can.
        vm.expectRevert(OarkelPool.NotRelayer.selector);
        pool.transact(sp.proof, sp.args, sp.ext);
        vm.prank(relayer);
        pool.transact(sp.proof, sp.args, sp.ext);
        assertEq(relayer.balance, 0.0002 ether);
        assertEq(pool.ethFees(), feesBefore + 0.0005 ether);

        // Bob finds his note (value 0.5 ETH) and takes it out.
        Note memory bobs = landed(sp, SIG_B);
        assertEq(bobs.value, 0.5 ether);
        SpendInput memory b;
        b.sig = SIG_B;
        b.notes = one(bobs);
        b.exitValue = 0.5 ether;
        b.recipient = bob;
        Spend memory sb = prove(b);
        pool.unshroud(sb.proof, sb.args, sb.ext);
        assertEq(bob.balance, 0.5 ether - FLAT_ETH);
    }

    function test_TwoNotesMergeToSelfPaysNoTransferFee() public {
        Note memory a = shroud(SIG_A, 0, 1 ether, 11);
        Note memory b = shroud(SIG_A, 0, 1 ether, 12);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = two(a, b);
        Spend memory sp = prove(s);
        assertEq(sp.args.transferFee, 0);
        pool.transact(sp.proof, sp.args, sp.ext);
        Note memory merged = landed(sp, SIG_A);
        assertEq(merged.value, a.value + b.value);
    }

    function test_TokenYieldReachesShroudedHolders() public {
        Note memory n = shroud(SIG_A, 1, 10_000 ether, 5);
        // 25 bps fee went back into the vault as yield.
        assertEq(pool.backing(), 10_000 ether);
        pool.donate(1_000 ether);
        uint256 worth = pool.valueOfShares(n.value);
        assertApproxEqAbs(worth, 11_000 ether, 1e7, "holder owns all yield");

        SpendInput memory s;
        s.sig = SIG_A;
        s.asset = 1;
        s.notes = one(n);
        s.exitValue = n.value;
        s.recipient = alice;
        s.relayerAddr = relayer;
        s.relayerFee = 8 ether;
        Spend memory sp = prove(s);
        vm.expectRevert(OarkelPool.NotRelayer.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        vm.prank(relayer);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        assertEq(token.balanceOf(alice), worth - FLAT_TOKEN - 8 ether);
        assertEq(token.balanceOf(relayer), 8 ether);
        assertEq(pool.totalShares(), 0);
        // The flat fee stays for the next holders.
        assertEq(pool.pendingYield() + pool.backing(), token.balanceOf(address(pool)));
    }

    function test_TokenSendBurnsFeeShares() public {
        Note memory a = shroud(SIG_A, 1, 10_000 ether, 5);
        Note memory b0 = shroud(SIG_B, 1, 10_000 ether, 6);
        uint256 bobWorthBefore = pool.valueOfShares(b0.value);
        SpendInput memory s;
        s.sig = SIG_A;
        s.asset = 1;
        s.notes = one(a);
        s.paySig = SIG_B;
        s.payValue = a.value / 2;
        Spend memory sp = prove(s);
        uint256 sharesBefore = pool.totalShares();
        pool.transact(sp.proof, sp.args, sp.ext);
        assertEq(pool.totalShares(), sharesBefore - sp.args.transferFee);
        assertGt(pool.valueOfShares(b0.value), bobWorthBefore, "burned fee shares raise every other share");
    }

    function test_RevertWhen_DoubleSpend() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.1 ether;
        s.recipient = alice;
        Spend memory sp = prove(s);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        vm.expectRevert(OarkelPool.NullifierSpent.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        // A fresh proof of the same note has the same nullifier.
        landed(sp, SIG_A);
        Spend memory again = prove(s);
        vm.expectRevert(OarkelPool.NullifierSpent.selector);
        pool.unshroud(again.proof, again.args, again.ext);
    }

    function test_RevertWhen_RecipientOrFeeTampered() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.5 ether;
        s.recipient = alice;
        s.relayerAddr = relayer;
        s.relayerFee = 0.0002 ether;
        Spend memory sp = prove(s);
        vm.startPrank(relayer);

        // Structs in memory are references: tamper one field, check, restore.
        sp.ext.recipient = bob;
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.ext.recipient = alice;

        sp.ext.relayerFee = 0.1 ether;
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.ext.relayerFee = 0.0002 ether;

        sp.args.exitValue = 0.6 ether;
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.args.exitValue = 0.5 ether;

        sp.args.asset = 1;
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.args.asset = 0;

        bytes memory enc = sp.ext.encryptedOutput0;
        sp.ext.encryptedOutput0 = hex"00";
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.ext.encryptedOutput0 = enc;

        sp.proof[100] = bytes1(uint8(sp.proof[100]) ^ 1);
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.proof[100] = bytes1(uint8(sp.proof[100]) ^ 1);

        // The untouched proof still works.
        pool.unshroud(sp.proof, sp.args, sp.ext);
    }

    function test_RevertWhen_FieldAliasOrUnknownRoot() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.5 ether;
        s.recipient = alice;
        Spend memory sp = prove(s);

        uint256 nf = sp.args.nullifiers[0];
        sp.args.nullifiers[0] = nf + pool.FIELD_SIZE();
        vm.expectRevert(OarkelPool.NotInField.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.args.nullifiers[0] = nf;

        uint256 root = sp.args.root;
        sp.args.root = 12345;
        vm.expectRevert(OarkelPool.UnknownRoot.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        sp.args.root = root;
        pool.unshroud(sp.proof, sp.args, sp.ext);
    }

    function test_RevertWhen_ProofReplayedOnAnotherPool() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.5 ether;
        s.recipient = alice;
        Spend memory sp = prove(s);
        // Same tree on a second pool: the external data hash binds the pool address.
        OarkelPool other = new OarkelPool(verifier, token, feeSink, SHROUD_BPS, TRANSFER_BPS, FLAT_ETH, FLAT_TOKEN);
        other.shroud{value: 1 ether}(0, 1 ether, ownerHashOf(SIG_A, 9), hex"01");
        assertEq(other.getLastRoot(), pool.getLastRoot());
        vm.expectRevert(OarkelPool.InvalidProof.selector);
        other.unshroud(sp.proof, sp.args, sp.ext);
    }

    function test_RevertWhen_SendCarriesRecipientOrUnshroudHasNone() public {
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.5 ether;
        s.recipient = alice;
        Spend memory sp = prove(s);
        vm.expectRevert(OarkelPool.BadRecipient.selector);
        pool.transact(sp.proof, sp.args, sp.ext);
    }

    function test_RevertWhen_RecipientRejectsEth() public {
        RejectEth sink = new RejectEth();
        Note memory n = shroud(SIG_A, 0, 1 ether, 9);
        SpendInput memory s;
        s.sig = SIG_A;
        s.notes = one(n);
        s.exitValue = 0.5 ether;
        s.recipient = address(sink);
        Spend memory sp = prove(s);
        vm.expectRevert(OarkelPool.EthTransferFailed.selector);
        pool.unshroud(sp.proof, sp.args, sp.ext);
        // Nothing was consumed: the note is still spendable.
        assertFalse(pool.nullifierSpent(sp.args.nullifiers[0]));
    }
}
